config/routes.rb
Rails.application.routes.draw do
  root to: "items#index"

  get '/items/export' => 'items#export', :as => :export_items
  get '/items/import' => 'items#import', :as => :import_items
  post '/items/import' => 'items#import_file', :as => :import_file_items

  post '/items/:id/softwares' => 'softwares#create'
  get 'items/:id/assign_user' => 'items#assign_user', as: :assign_user
  get 'items/:id/process_user/:user_id/' => 'items#process_user', as: :process_user

  resources :items do
    resources :softwares, only: [:new, :create]
  end

  resources :softwares, only: [:index, :show, :edit, :update, :destroy]

  devise_for :users
end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id           :integer          not null, primary key
#  serial       :string(255)
#  name         :string(255)
#  manufacturer :string(255)
#  ubt_serial   :string(255)
#  description  :string(255)
#  user_id      :integer
#  created_at   :datetime
#  updated_at   :datetime
#

class Item < ActiveRecord::Base
  belongs_to :user
  has_many :software

  validates :serial, uniqueness: true,
    unless: :blank_serial?

  def blank_serial?
    if serial == nil or serial == ''
      true
    else
      false
    end
  end

  def self.to_csv
    CSV.generate do |csv|
      @header = %w{serial name manufacturer ubt_serial description}
      csv << @header
      all.each do |item|
        csv << item.attributes.values_at("serial", "name", "manufacturer", "ubt_serial", "description")
      end
    end
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      @item = Item.new(row.to_hash)
      @item.save
    end
  end

end

app/models/software.rb
# == Schema Information
#
# Table name: softwares
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  serial     :string(255)
#  notes      :string(255)
#  item_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Software < ActiveRecord::Base
  belongs_to :item
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy, :assign_user]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @softwares = @item.software
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # GET /items/export
  def export
    @items = Item.all
    send_data @items.to_csv
  end
  # GET /items/import
  def import
  end
  # POST /items/import
  def import_file
    begin
      Item.import(params[:file])
      redirect_to root_url, notice: "Products imported. Duplicates are Ignored."
    rescue
      redirect_to root_url, notice: "Invalid CSV file format."
    end
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def assign_user
    @users = User.all
  end

  def process_user
    @item = Item.find(params[:id])
    @user = User.find(params[:user_id])
    @item.user_id = @user.id
    if @item.save
      redirect_to item_path(@item)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:serial, :name, :manufacturer, :ubt_serial, :description, :user_id)
    end
end

app/controllers/softwares_controller.rb
class SoftwaresController < ApplicationController
  before_action :set_software, only: [:show, :edit, :update, :destroy]

  # GET /softwares
  # GET /softwares.json
  def index
    @softwares = Software.all
  end

  # GET /softwares/1
  # GET /softwares/1.json
  def show
  end

  # GET /softwares/new
  def new
    @item = Item.find(params[:item_id])
    @software = Software.new
  end

  # GET /softwares/1/edit
  def edit
  end

  # POST /softwares
  # POST /softwares.json
  def create
    @software = Software.new(software_params)
    @item = Item.find(params[:id])
    @software.item = @item
    respond_to do |format|
      if @software.save
        format.html { redirect_to @software, notice: 'Software was successfully created.' }
        format.json { render :show, status: :created, location: @software }
      else
        format.html { render :new }
        format.json { render json: @software.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /softwares/1
  # PATCH/PUT /softwares/1.json
  def update
    respond_to do |format|
      if @software.update(software_params)
        format.html { redirect_to @software, notice: 'Software was successfully updated.' }
        format.json { render :show, status: :ok, location: @software }
      else
        format.html { render :edit }
        format.json { render json: @software.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /softwares/1
  # DELETE /softwares/1.json
  def destroy
    @software.destroy
    respond_to do |format|
      format.html { redirect_to softwares_url, notice: 'Software was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_software
      @software = Software.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def software_params
      params.require(:software).permit(:name, :serial, :notes, :item_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/softwares_helper.rb
module SoftwaresHelper
end

app/views/items/_form.html.erb
<div class="row">
  <div class="col-lg-6">
    <%= form_for(@item, class: "form-horizontal edit-stock") do |f| %>
      <% if @item.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

          <ul>
          <% @item.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :serial, class: "col-sm-3 control-label" %>
        <div class="col-sm-9">
          <%= f.text_field :serial, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :name, class: "col-sm-3 control-label" %>
        <div class="col-sm-9">
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :manufacturer, class: "col-sm-3 control-label" %>
        <div class="col-sm-9">
          <%= f.text_field :manufacturer, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :ubt_serial, class: "col-sm-3 control-label" %>
        <div class="col-sm-9">
          <%= f.text_field :ubt_serial, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :description, class: "col-sm-3 control-label" %>
        <div class="col-sm-9">
          <%= f.text_field :description, class: "form-control" %>
        </div>
      </div>
      <div class="actions col-sm-offset-3 col-sm-9">
        <%= f.submit class: "btn btn-sm btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/items/_item.html.erb
<p>
  <strong>Serial:</strong>
  <%= @item.serial %>
</p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @item.manufacturer %>
</p>

<p>
  <strong>Ubt serial:</strong>
  <%= @item.ubt_serial %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

app/views/items/_items.html.erb
<div class="row">
  <div class="col-lg-4">
    <input id="filter" type="text" class="form-control" placeholder="Search For...">
  </div>
</div>
<div class="row">
  <div class="col-lg-12">
    <table class="table table-striped tablesorter" id="sorttable">
      <thead>
        <tr>
          <th>Serial</th>
          <th>Name</th>
          <th>Ubt serial</th>
          <th>Description</th>
          <th>User</th>
          <th></th>
        </tr>
      </thead>
      <tbody class="searchable">
        <% @items.each do |item| %>
          <tr>
            <td><%= item.serial %></td>
            <td><%= item.name %></td>
            <td><%= item.ubt_serial %></td>
            <td><%= item.description %></td>
            <td>
              <% if item.user != nil %>
                <%= item.user.email %>
              <% end %>
            </td>
            <td>
              <div class="btn-group">
                <%= link_to 'Show', item, class: "btn btn-xs btn-info" %>
                <%= link_to 'Edit', edit_item_path(item), class: "btn btn-xs btn-info" %>
                <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-danger" %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/items/_software.html.erb
<div class="row">
  <div class="col-lg-4">
    <input id="filter" type="text" class="form-control" placeholder="Search For...">
  </div>
</div>
<div class="row">
  <div class="col-lg-12">
    <table class="table table-striped table-hover tablesorter" id="sortable">
      <thead>
        <tr>
          <th>Name</th>
          <th>Serial</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody class="searchable">
        <% @softwares.each do |software| %>
          <tr>
            <td><%= software.name %></td>
            <td><%= software.serial %></td>
            <td><%= link_to 'Show', software %></td>
            <td><%= link_to 'Edit', edit_software_path(software) %></td>
            <td><%= link_to 'Destroy', software, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/items/assign_user.html.erb
<div class="page-header">
  <h1>Assign User for Item</h1>
</div>

<div class="content">
  <div class="row">
    <div class="col-lg-4">
      <input id="filter" type="text" class="form-control" placeholder="Search For...">
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <table class="table table-striped table-hover tablesorter" id="sorttable">
        <thead>
          <tr>
            <th>User</th>
            <th></th>
          </tr>
        </thead>
        <tbody class="searchable">
          <% @users.each do |user| %>
            <tr>
              <td><%= user.email %></td>
              <td>
                <div class="btn-group">
                  <%= link_to "Assign", process_user_path(@item, user), class: "btn btn-xs btn-success" %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="btn-group">

  </div>
</div>

app/views/items/edit.html.erb
<div class="page-header">
  <h1>Editing item</h1>
</div>
<div class="content">
  <%= render 'form' %>
  <div class="btn-group">
    <%= link_to 'Show', @item, class: "btn btn-sm btn-info" %>
    <%= link_to 'Back', items_path, class: "btn btn-sm btn-info" %>
  </div>
</div>

app/views/items/import.html.erb
<div class="page-header">
  <h3>Import a CSV File</h3>
</div>
<div class="container">
  <%= form_tag import_items_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import CSV" %>
  <% end %>
</div>

app/views/items/index.html.erb
<div class="page-header">
  <h1>Listing items</h1>
</div>

<div id="content">
  <%= render 'items' %>
  <br>
  <div class="btn-group" >
    <%= link_to 'New Item', new_item_path, class: "btn btn-sm btn-success" %>
  </div>
</div>

app/views/items/new.html.erb
<div class="page-header">
  <h1>New item</h1>
</div>
<div class="content">
  <%= render 'form' %>

  <%= link_to 'Back', items_path, class: "btn btn-sm btn-info" %>
</div>

app/views/items/show.html.erb
<div class="page-header">
  <h1>Showing Details for <%= @item.serial%></h1>
  <% if @item.user_id != nil %>
    <h4>Assigned to <%= @item.user.email %></h4>
  <% end %>
</div>
<div class="paragraph">
  <div class="row">
    <div class="col-sm-6">
      <%= render 'item' %>
    </div>
    <div class="col-sm-6">
      <%= render 'software' %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-6">
      <div class="btn-group">
        <% if @item.user_id == nil %>
          <%= link_to "Assign to User", assign_user_path, class: "btn btn-sm btn-success" %>
        <% end %>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="btn-group">
        <%= link_to 'New Software', new_item_software_path(@item), class: "btn btn-sm btn-success" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-6">
      <div class="btn-group">
        <%= link_to 'Edit', edit_item_path(@item), class: "btn btn-sm btn-info" %>
        <%= link_to 'Back', items_path, class: "btn btn-sm btn-info" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class ="content container">
    <hr style="height:5px;color:#18232d;"
    <br />
    <p>
      Eneraque Pty Ltd
    </p>
  </div>
</footer>

app/views/layouts/_header.html.erb
  <div class="navbar header" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Enervintory', root_path, :class => "navbar-brand" %>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li><%= link_to "Item Register", items_path %></li>
            <li><%= link_to "Software Register", softwares_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Analysis Tools <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Users</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Data Tools</li>
                <li><%= link_to "Export", export_items_path %></li>
                <li><%= link_to "Import", import_items_path %></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to current_user.email, edit_user_registration_path, class: "navbar-link" %></li>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "navbar-link" %></li>
          <% else %>
            <li><%= link_to "Register", new_user_registration_path, class: "navbar-link" %></li>
            <li><%= link_to "Log In", new_user_session_path, class: "navbar-link" %></li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div><!--/.container-fluid -->
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Enervintory</title>
  <link href='http://fonts.googleapis.com/css?family=Istok+Web' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div class="container errors main-body">
  <% if notice %>
    <p id="notice"><%= flash[:notice] %></p>
  <% end %>
  <% if alert %>
    <p id="alert" style="color:red;"><%= flash[:alert] %></p>
  <% end %>
</div>
<div class="container main-body">
  <%= yield %>
</div>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/softwares/_form.html.erb
<div class="row">
  <div class="col-lg-6">
    <%= form_for [@item, @software], http: { class: "table-horizontal"} do |f| %>
      <% if @software.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@software.errors.count, "error") %> prohibited this software from being saved:</h2>

          <ul>
          <% @software.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :name, class: "control-label col-sm-3" %>
        <div class="col-sm-9">
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>
      <div class="field">
        <%= f.label :serial, class: "control-label col-sm-3" %>
        <div class="col-sm-9">
          <%= f.text_field :serial, class: "form-control" %>
        </div>
      </div>
      <div class="field">
        <%= f.label :notes, class: "control-label col-sm-3" %>
        <div class="col-sm-9">
          <%= f.text_field :notes, class: "form-control" %>
        </div>
      </div>
      <div class="actions col-sm-offset-3 col-sm-offset-9">
        <%= f.submit class: "btn btn-sm btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/softwares/_softwares.html.erb
<div class="row">
  <div class="col-lg-4">
    <input id="filter" type="text" class="form-control" placeholder="Search For...">
  </div>
</div>
<div class="row">
  <div class="col-lg-12">
    <table class="table table-striped table-hover tablesorter" id="sortable">
      <thead>
        <tr>
          <th>Name</th>
          <th>Serial</th>
          <th>Notes</th>
          <th>Item</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody class="searchable">
        <% @softwares.each do |software| %>
          <tr>
            <td><%= software.name %></td>
            <td><%= software.serial %></td>
            <td><%= software.notes %></td>
            <td>
              <% if software.item != nil %>
                <%= link_to software.item.name, software.item %>
              <% end %>
            </td>
            <td>
              <div class="btn-group">
                <%= link_to 'Show', software, class: "btn btn-xs btn-info" %>
                <%= link_to 'Edit', edit_software_path(software), class: "btn btn-xs btn-info" %>
                <%= link_to 'Destroy', software, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-danger" %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/softwares/edit.html.erb
<div class="page-header">
  <h1>Editing software</h1>
</div>
<div class="content">
  <%= render 'form' %>
  <div class="btn-group">
    <%= link_to 'Show', @software %>
    <%= link_to 'Back', softwares_path %>
  </div>
</div>

app/views/softwares/index.html.erb
<div class="page-header">
<h1>Listing softwares</h1>
</div>
<div class="content">
  <%= render 'softwares' %>
</div>

app/views/softwares/new.html.erb
<div class="page-header">
  <h1>New software</h1>
</div>
<div class="content">
  <%= render 'form' %>

  <%= link_to 'Back', softwares_path, class: "btn btn-sm btn-info" %>
</div>

app/views/softwares/show.html.erb
<div class="page-header">
  <h1>Showing Detail for <%= @software.name %>
</div>
<div class="content">
  <p>
    <strong>Serial:</strong>
    <%= @software.serial %>
  </p>

  <p>
    <strong>Notes:</strong>
    <%= @software.notes %>
  </p>

  <p>
    <strong>Item:</strong>
    <%= @software.item %>
  </p>
  <div class="btn-group">
    <%= link_to 'Edit', edit_software_path(@software), class: "btn btn-sm btn-info" %>
    <%= link_to 'Back', softwares_path, class: "btn btn-sm btn-info" %>
  </div>
</div>